`timescale 1ns / 1ps

module tb_sort32_random_ps_injection;

    // ----------------------------------------------------------------
    // Memory layout shared with verify.ipynb
    // ----------------------------------------------------------------
    // DMEM 0x00 - 0x7C: 32 signed input/output integers
    // DMEM 0x80       : DONE status flag
    // DMEM 0x84       : right-side guard word
    //
    // test_sort.hex: instruction-memory image generated by Jupyter
    // data.mem:      data-memory snapshot generated by Jupyter
    // ----------------------------------------------------------------

    localparam integer IMEM_WORDS = 256;
    localparam integer DMEM_WORDS = 256;

    localparam integer ARRAY_BASE_INDEX = 0;
    localparam integer ARRAY_LENGTH = 32;
    localparam integer DONE_INDEX = 32;
    localparam integer RIGHT_GUARD_INDEX = 33;

    localparam integer MAX_CYCLES = 200000;

    localparam [31:0] DONE_MAGIC = 32'hCAFEBABE;
    localparam [31:0] RIGHT_GUARD_VALUE = 32'h2468ACE0;
    localparam [31:0] NOP_INSTRUCTION = 32'h00000013;

    reg clk;
    reg sys_resetn;
    reg run_resetn;

    wire        imem_enb;
    wire [3:0]  imem_web;
    wire [31:0] imem_addrb;
    wire [31:0] imem_dinb;
    reg  [31:0] imem_doutb;

    wire        dmem_enb;
    wire [3:0]  dmem_web;
    wire [31:0] dmem_addrb;
    wire [31:0] dmem_dinb;
    reg  [31:0] dmem_doutb;

    reg [31:0] imem [0:IMEM_WORDS-1];
    reg [31:0] dmem [0:DMEM_WORDS-1];
    reg [31:0] expected [0:ARRAY_LENGTH-1];

    integer i;
    integer j;
    integer cycle_count;
    integer error_count;
    integer negative_count;
    integer positive_count;

    reg [31:0] temp;
    reg done_seen;

    rv_pipeline dut (
        .clk        (clk),
        .sys_resetn (sys_resetn),
        .run_resetn (run_resetn),

        .imem_enb   (imem_enb),
        .imem_web   (imem_web),
        .imem_addrb (imem_addrb),
        .imem_dinb  (imem_dinb),
        .imem_doutb (imem_doutb),

        .dmem_enb   (dmem_enb),
        .dmem_web   (dmem_web),
        .dmem_addrb (dmem_addrb),
        .dmem_dinb  (dmem_dinb),
        .dmem_doutb (dmem_doutb)
    );

    // 50 MHz clock.
    always #10 clk = ~clk;

    // ----------------------------------------------------------------
    // Synchronous instruction BRAM model
    // ----------------------------------------------------------------
    always @(posedge clk) begin
        if (imem_enb)
            imem_doutb <= imem[imem_addrb[9:2]];
    end

    // ----------------------------------------------------------------
    // Synchronous data BRAM model with byte write enables
    // ----------------------------------------------------------------
    always @(posedge clk) begin
        if (dmem_enb) begin
            if (dmem_web[0])
                dmem[dmem_addrb[9:2]][7:0] <= dmem_dinb[7:0];

            if (dmem_web[1])
                dmem[dmem_addrb[9:2]][15:8] <= dmem_dinb[15:8];

            if (dmem_web[2])
                dmem[dmem_addrb[9:2]][23:16] <= dmem_dinb[23:16];

            if (dmem_web[3])
                dmem[dmem_addrb[9:2]][31:24] <= dmem_dinb[31:24];

            dmem_doutb <= dmem[dmem_addrb[9:2]];
        end
    end

    task check_sorted_word;
        input integer array_index;
        input [31:0] expected_value;

        reg [31:0] actual_value;
        begin
            actual_value =
                dmem[ARRAY_BASE_INDEX + array_index];

            if (actual_value !== expected_value) begin
                $display(
                    "FAIL: index %0d, address 0x%08X, expected 0x%08X, got 0x%08X",
                    array_index,
                    (ARRAY_BASE_INDEX + array_index) * 4,
                    expected_value,
                    actual_value
                );

                error_count = error_count + 1;
            end
        end
    endtask

    initial begin
        clk = 1'b0;
        sys_resetn = 1'b0;
        run_resetn = 1'b0;

        imem_doutb = 32'b0;
        dmem_doutb = 32'b0;

        done_seen = 1'b0;
        error_count = 0;
        negative_count = 0;
        positive_count = 0;

        // Initialize the full behavioral memories before loading files.
        for (i = 0; i < IMEM_WORDS; i = i + 1)
            imem[i] = NOP_INSTRUCTION;

        for (i = 0; i < DMEM_WORDS; i = i + 1)
            dmem[i] = 32'b0;

        // Load the exact machine-code and data snapshots produced by
        // verify.ipynb.
        $readmemh("test_sort.hex", imem, 0, 63);
        $readmemh("data.mem", dmem, 0, 63);

        // Match the PS-side preparation sequence:
        // reset DONE before releasing the processor and initialize the
        // memory guard immediately after the status word.
        dmem[DONE_INDEX] = 32'b0;
        dmem[RIGHT_GUARD_INDEX] = RIGHT_GUARD_VALUE;

        // Copy the 32 injected values before the processor modifies DMEM.
        // The testbench then creates an independent signed reference sort.
        for (i = 0; i < ARRAY_LENGTH; i = i + 1) begin
            expected[i] =
                dmem[ARRAY_BASE_INDEX + i];

            if ($signed(dmem[ARRAY_BASE_INDEX + i]) < 0)
                negative_count = negative_count + 1;
            else if ($signed(dmem[ARRAY_BASE_INDEX + i]) > 0)
                positive_count = positive_count + 1;
        end

        if (negative_count == 0) begin
            $display(
                "FAIL: data.mem does not contain a negative signed integer"
            );

            error_count = error_count + 1;
        end

        if (positive_count == 0) begin
            $display(
                "FAIL: data.mem does not contain a positive signed integer"
            );

            error_count = error_count + 1;
        end

        // Signed bubble sort used only as the simulation reference model.
        for (i = 0; i < ARRAY_LENGTH - 1; i = i + 1) begin
            for (
                j = 0;
                j < ARRAY_LENGTH - 1 - i;
                j = j + 1
            ) begin
                if (
                    $signed(expected[j]) >
                    $signed(expected[j + 1])
                ) begin
                    temp = expected[j];
                    expected[j] = expected[j + 1];
                    expected[j + 1] = temp;
                end
            end
        end

        if (error_count != 0) begin
            $display(
                "FAIL: invalid randomized input data"
            );

            $finish;
        end

        // Release the system reset first, then release the run reset.
        #100;
        sys_resetn = 1'b1;

        #100;
        run_resetn = 1'b1;

        // Wait for the processor to write 0xCAFEBABE to DMEM 0x80.
        begin : wait_for_done
            for (
                cycle_count = 0;
                cycle_count < MAX_CYCLES;
                cycle_count = cycle_count + 1
            ) begin
                @(posedge clk);

                if (dmem[DONE_INDEX] === DONE_MAGIC) begin
                    done_seen = 1'b1;
                    disable wait_for_done;
                end
            end
        end

        // Stop the processor before checking the final memory image.
        run_resetn = 1'b0;
        @(posedge clk);

        if (!done_seen) begin
            $display(
                "FAIL: timeout waiting for DONE magic 0x%08X at DMEM address 0x00000080",
                DONE_MAGIC
            );

            $finish;
        end

        $display(
            "INFO: DONE magic 0x%08X detected after %0d cycles",
            dmem[DONE_INDEX],
            cycle_count
        );

        if (dmem[RIGHT_GUARD_INDEX] !== RIGHT_GUARD_VALUE) begin
            $display(
                "FAIL: right guard expected 0x%08X, got 0x%08X",
                RIGHT_GUARD_VALUE,
                dmem[RIGHT_GUARD_INDEX]
            );

            error_count = error_count + 1;
        end

        for (i = 0; i < ARRAY_LENGTH; i = i + 1)
            check_sorted_word(i, expected[i]);

        if (error_count == 0) begin
            $display(
                "PASS: exactly 32 random signed integers sorted in place at addresses 0x00 through 0x7C"
            );

            $display(
                "PASS: positive/negative input, DONE magic, and memory guard checks passed"
            );
        end
        else begin
            $display(
                "FAIL: sorting simulation completed with %0d error(s)",
                error_count
            );
        end

        $finish;
    end

endmodule
